name: 构建内核

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: '选择要构建的内核版本'
        required: true
        type: choice
        options:
          - '6.1.57'
          - '6.1.75'
          - '6.1.115 (天玑特供)'
          - '6.1.118'
          - '6.1.128 (天玑特供)'
      ksu_type:
        description: 'KernelSU分支(SukiSU Ultra/KernelSU Next,默认SukiSU Ultra)'
        required: true
        type: choice
        default: 'sukisu'
        options:
          - 'sukisu'
          - 'ksunext'
      hook_method:
        description: hook模式(大部分情况manual即可，若新版manual钩子出现问题可尝试syscall, 少数需切换sus su模式的场景才需要kprobes钩子)
        required: true
        type: choice
        default: 'manual'
        options:
          - 'manual'
          - 'syscall'
          - 'kprobes'
      kpm_enable:
        description: '是否开启kpm(仅对sukisu生效;可能轻微增加耗电，不需要可关闭)'
        required: true
        type: choice
        default: 'true'
        options:
          - 'true'
          - 'false'
      lz4_enable:
        description: '是否安装 lz4 1.10.0+zstd 1.5.7 补丁及 LZ4KD 补丁(0=均不安装,1=安装lz4&zstd补丁,2=安装lz4kd补丁,3=均安装,默认1)'
        required: true
        type: choice
        default: '1'
        options:
          - '0'
          - '1'
          - '2'
          - '3'
      bbr_enable:
        description: "是否启用bbr算法(优化上行数据,对手机日用无太大意义甚至可能负优化;false关闭,true仅加入算法,default设为默认)"
        required: true
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'true'
          - 'default'
      better_net:
        description: '是否开启网络功能增强优化配置(优化代理连接,IPV6等功能)'
        required: true
        type: choice
        default: 'true'
        options:
          - 'true'
          - 'false'
      ssg_rekernel_enable:
        description: '是否启用三星SSG IO调度器及Re-Kernel支持(0=均不安装,1=安装SSG IO调度器,2=安装Re-Kernel,3=均安装,默认1)'
        required: true
        type: choice
        default: '1'
        options:
          - '0'
          - '1'
          - '2'
          - '3'
      baseband_guard:
        description: '是否开启内核级基带保护(阻止一切对非用户分区的写入，有效防止格机)'
        required: true
        type: boolean
        default: false
      kernel_suffix:
        description: '内核后缀(留空默认,开头别加连字符,勿加空格等影响指令运行的保留字符)'
        required: false
        type: string
        default: ''

jobs:
  dispatch-build:
    runs-on: ubuntu-latest
    steps:
      - name: 加速构建 6.1.57
        if: github.event.inputs.kernel_version == '6.1.57'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'fastbuild_6.1.57.yml',
              ref: 'main',
              inputs: {
                ksu_type: '${{ github.event.inputs.ksu_type }}',
                hook_method: '${{ github.event.inputs.hook_method }}',
                kpm_enable: '${{ github.event.inputs.kpm_enable }}',
                lz4_enable: '${{ github.event.inputs.lz4_enable }}',
                bbr_enable: '${{ github.event.inputs.bbr_enable }}',
                better_net: '${{ github.event.inputs.better_net }}',
                ssg_rekernel_enable: '${{ github.event.inputs.ssg_rekernel_enable }}',
                baseband_guard: '${{ github.event.inputs.baseband_guard }}',
                kernel_suffix: '${{ github.event.inputs.kernel_suffix }}'
              }
            })

      - name: 加速构建 6.1.75
        if: github.event.inputs.kernel_version == '6.1.75'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'fastbuild_6.1.75.yml',
              ref: 'main',
              inputs: {
                ksu_type: '${{ github.event.inputs.ksu_type }}',
                hook_method: '${{ github.event.inputs.hook_method }}',
                kpm_enable: '${{ github.event.inputs.kpm_enable }}',
                lz4_enable: '${{ github.event.inputs.lz4_enable }}',
                bbr_enable: '${{ github.event.inputs.bbr_enable }}',
                better_net: '${{ github.event.inputs.better_net }}',
                ssg_rekernel_enable: '${{ github.event.inputs.ssg_rekernel_enable }}',
                baseband_guard: '${{ github.event.inputs.baseband_guard }}',
                kernel_suffix: '${{ github.event.inputs.kernel_suffix }}'
              }
            })
     
      - name: 加速构建 6.1.115
        if: github.event.inputs.kernel_version == '6.1.115 (天玑特供)'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'fastbuild_6.1.115.yml',
              ref: 'main',
              inputs: {
                ksu_type: '${{ github.event.inputs.ksu_type }}',
                hook_method: '${{ github.event.inputs.hook_method }}',
                kpm_enable: '${{ github.event.inputs.kpm_enable }}',
                lz4_enable: '${{ github.event.inputs.lz4_enable }}',
                bbr_enable: '${{ github.event.inputs.bbr_enable }}',
                better_net: '${{ github.event.inputs.better_net }}',
                ssg_rekernel_enable: '${{ github.event.inputs.ssg_rekernel_enable }}',
                baseband_guard: '${{ github.event.inputs.baseband_guard }}',
                kernel_suffix: '${{ github.event.inputs.kernel_suffix }}'
              }
            })

      - name: 加速构建 6.1.118
        if: github.event.inputs.kernel_version == '6.1.118'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'fastbuild_6.1.118.yml',
              ref: 'main',
              inputs: {
                ksu_type: '${{ github.event.inputs.ksu_type }}',
                hook_method: '${{ github.event.inputs.hook_method }}',
                kpm_enable: '${{ github.event.inputs.kpm_enable }}',
                lz4_enable: '${{ github.event.inputs.lz4_enable }}',
                bbr_enable: '${{ github.event.inputs.bbr_enable }}',
                better_net: '${{ github.event.inputs.better_net }}',
                ssg_rekernel_enable: '${{ github.event.inputs.ssg_rekernel_enable }}',
                baseband_guard: '${{ github.event.inputs.baseband_guard }}',
                kernel_suffix: '${{ github.event.inputs.kernel_suffix }}'
              }
            })

      - name: 加速构建 6.1.128
        if: github.event.inputs.kernel_version == '6.1.128 (天玑特供)'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'fastbuild_6.1.128.yml',
              ref: 'main',
              inputs: {
                ksu_type: '${{ github.event.inputs.ksu_type }}',
                hook_method: '${{ github.event.inputs.hook_method }}',
                kpm_enable: '${{ github.event.inputs.kpm_enable }}',
                lz4_enable: '${{ github.event.inputs.lz4_enable }}',
                bbr_enable: '${{ github.event.inputs.bbr_enable }}',
                better_net: '${{ github.event.inputs.better_net }}',
                ssg_rekernel_enable: '${{ github.event.inputs.ssg_rekernel_enable }}',
                baseband_guard: '${{ github.event.inputs.baseband_guard }}',
                kernel_suffix: '${{ github.event.inputs.kernel_suffix }}'
              }
            })